In [3]:
'''1. solve the following system:
	x1-2x2+x3=0
	2x2-8x3=0
	-4x1+5x2+7x2=0'''

import numpy as np
# the coefficient matrix A
A = np.array([[1, -2, 1],
[0, 2, -8],[-4, 5, 7]])
#  the constant vector B
B = np.array([0, 0, 0])
# system of equations Ax = b using numpy.linalg.solve
x = np.linalg.solve(A, B)
print(x)

# the system of equations is x1 = -0, x2 = 0, and x3 = -0.


[-0.  0. -0.]


In [4]:
'''# 2.Transform the following matrix into row echelon form as:
	 1 1 2
	 1 2 3
	 3 4 5'''

import numpy as np
#define matrix as input
X= np.array([[1, 1, 2], [1, 2, 3], [3, 4, 5]])
#transform the matrix into row echelon form
for i in range(3):
    if X[i,i] == 0:
        for j in range(i+1, 3):
            if X[j,i] != 0:
                X[[i,j]] = X[[j,i]]
                break
# from the rows below it to make all elements below the pivot zero
for j in range(i+1, 3):
        fact = X[j,i] / X[i,i]
        X[j] = X[j] - fact * X[i]

# Print the resulting row echelon form
print(X)

[[1 1 2]
 [1 2 3]
 [3 4 5]]


In [7]:
'''3. Find the eigen value and eigen vector of the matrix:
	Y=[5 2
       2 1]'''
    
import numpy as np 
# input as a matric
Y = np.array([[5, 2], [2, 1]])
# Find the eigenvalues & eigenvectors
print("eigenvalues")
eigenvals, eigenvects = np.linalg.eig(Y)
for eigenval in eigenvals:
    print(eigenval)

print("\neigenvectors")
for i, eigenvect in enumerate(eigenvects.T):
    print("eigenvector {}:".format(i+1), eigenvect)
    

eigenvalues
5.82842712474619
0.17157287525380982

eigenvectors
eigenvector 1: [0.92387953 0.38268343]
eigenvector 2: [-0.38268343  0.92387953]


In [2]:
'''4. Identify the parametric vector form of the following matrix :
	A= 1  0 -8 -7
	   0  1  4  3
	   0  0  0  0'''

import numpy as np 
Z = np.array([[1, 0, -8, -7], [0, 1, 4, 3]])
#pivot elemint 
pivot = [0, 1]
#free variables
free_var = [2, 3]
#sol list store so we create a list is sol
sol = []
for i in range(len(free_var)):
    # solution vector = soln
    soln = np.zeros(Z.shape[1])
    # set of piovt element 
    soln[pivot] = np.random.rand(len(pivot))
    #set of free variable 
    soln[free_var[i]] = 1
    soln[free_var[1-i]] = -((7/8)*soln[0] - (1/8)*soln[1])/(3/4)
    # store the value in var solns
    sol.append(soln)
print(sol)
    




[array([0.05006953, 0.74963992, 1.        , 0.06652553]), array([ 0.39573303,  0.24785363, -0.4203796 ,  1.        ])]


In [4]:
'''5.Compute the parametric vector form of the soolution set of 
A.x=0, where
	A= 1  -3
	   2  -6'''

import numpy as np

#the matrix A
A = np.array([[1, -3], [2, -6]])
# the null space of A using the SVD method
T, U, V = np.linalg.svd(A)
null_space = V[-1, :]
# the parametric vector form 
print("x = t *", null_space)


x = t * [-0.9486833  -0.31622777]


In [5]:
'''6. What is the solution set of A.x=b,where
	A= 1 -1 2
	  -2 2 -4, and 
	b=  1 
	   -2'''
import numpy as np

# the matrix A
A = np.array([[1, -3], [2, -6]])
# find the null space of A using the SVD method
U, s, V = np.linalg.svd(A)
null_space = V[-1, :]
# Print the parametric vector form 
print("x = t *", null_space)




x = t * [-0.9486833  -0.31622777]


In [7]:
'''7.Check the linear independence 
	 2  4 10
	 3 -7 11
	-1  4 10'''

import numpy as np
# matrix A
A = np.array([[2, 4, 10], [3, -7, 11], [-1, 4, 10]])
#rank of matrix
rank = np.linalg.matrix_rank(A)
if rank == A.shape[1]:
    print("The vectors are linearly independent.")
else:
    print("The vectors are linearly dependent.")

The vectors are linearly independent.


In [6]:
'''8. Find a spanning set for the null space of the matrix:
	A= 2  3 -8 -5
	   -1 2 -3 -8'''
    
import numpy as np
# the matrix A
A = np.array([[2, 3, -8, -5], [-1, 2, -3, -8]])
# find the null space of A using the SVD method
t, u, V = np.linalg.svd(A)
null_space = V[-2:, :].T
# spanning set for the null space of A
print("A null space =", null_space)


A null space = [[ 0.88070755 -0.13591122]
 [ 0.08004516  0.95150275]
 [ 0.40031614  0.21361026]
 [-0.24019571  0.17476074]]


In [8]:
'''9. To find pivots of the matrix:
	A= 1 -2 1
	   1 -1 2
	   0 -2 2'''


import numpy as np
from scipy.linalg import lu
# create matrix A
A = np.array([[1, -2, 1], [1, -1, 2], [0, -2, 2]])
# LU factorization
x, y, z = lu(A)
print("Pivots of matrix ")
print(np.where(np.diag(z) != 0)[0])


Pivots of matrix 
[0 1 2]


In [7]:
'''10. fIND A Basis of the subspace 
	V=span{(1   (2  (0  (-1
		  -2  -3   4   5
		  2), 4),  0), -1)'''
    
import numpy as np
# the matrix A
A = np.array([[2, 3, -8, -5], [-1, 2, -3, -8]])
# find the null space of A using the SVD method
t, u, V = np.linalg.svd(A)
null_space = V[-2:, :].T
# spanning set for the null space of A
print("A null space =", null_space)

    


A null space = [[ 0.88070755 -0.13591122]
 [ 0.08004516  0.95150275]
 [ 0.40031614  0.21361026]
 [-0.24019571  0.17476074]]


In [1]:
'''11.compute the column space and the null space of :
A=[1 1 
   1 1 
   1 1]'''

from sympy import Matrix 

A = [[1, 1,], [1,1], [1,1]] 
A = Matrix(A) 
NullSpace = A.nullspace()  
  
NullSpace = Matrix(NullSpace)
print("Null Space : ", NullSpace) 
print(A * NullSpace)

Null Space :  Matrix([[-1], [1]])
Matrix([[0], [0], [0]])


In [9]:
'''12.Compute the rank and nullity of the following matrix
	A= 1 2 0 -1
        -2 -3 4 5
	  2 4 0  -2'''

import numpy as np
# create matrix A
A = np.array([[1, 2, 0, -1],
              [-2, -3, 4, 5],
              [2, 4, 0, -2]])

# calculate  the rank and nullity
rank = np.linalg.matrix_rank(A)
nullity = A.shape[1] - rank
print("Rank of A: ", rank)
print("Nullity of A: ",nullity)


Rank of A:  2
Nullity of A:  2
